# Generated by Django 4.1.7 on 2023-03-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=40)),
                ('teacher_email', models.CharField(max_length=40)),
            ],
        ),
    ]
